language: elixir
sudo: false
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.3
    - elixir: 1.7.3
      otp_release: 21.1
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - gazler@gmail.com
script:
  - if [[ `elixir -v` = *"1.7"* ]]; then mix format --check-formatted; fi
  - mix test
